// Folgender Code wirft einen ReferenceError

try {
  meineLieblingsFunktion();
} catch (e) {
  console.log(e);
}
